defaults:
  - _self_

task: classification

model: rf
tune: true
smote: false
gan: false
shap: false

cv:
  folds: 5

gan_params:
  epochs: 300
  gan_0: 10
  gan_1: 20

regression:
  use_clf: true
  predict_proba: true

tuning:
  method: optuna
  trials: 50


# Feature engineering
fe:
  age_gap: true
  age_bin: true

  drop_columns:
    donor_ABO: true
    recipient_ABO: true
    recipient_rh: true
    recipient_gender: true
    recipient_age_int: true
    recipient_age_below_10: true
    donor_age_below_35: true
    recipient_CMV: true
    donor_CMV: true
    disease_group: true
